
apiVersion: scaffolder.backstage.io/v1beta3

kind: Template

metadata:

  name: create-openstack-vm

  title: Create OpenStack Virtual Machine

  description: Provision an Ubuntu VM on OpenStack using Crossplane

  tags:

    - openstack

    - crossplane

    - gitops

spec:

  owner: platform-team

  type: service



  parameters:

    - title: Provide VM Details

      required:

        - instanceName

        - flavorName

      properties:

        instanceName:

          title: Instance Name

          type: string

          description: Unique name for your virtual machine

          ui:autofocus: true

          ui:options:

            help: Use lowercase letters and hyphens (e.g., dev-vm-01)

        flavorName:

          title: VM Flavor Size

          type: string

          default: m1.small

          enum:

            - m1.nano

            - m1.micro

            - m1.tiny

            - m1.small

            - m1.medium

            - m1.large

            - m1.xlarge



  steps:

    - id: fetch-base

      name: Generate Crossplane Manifest

      action: fetch:template

      input:

        url: ./skeleton

        values:

          instanceName: ${{ parameters.instanceName }}

          flavorName: ${{ parameters.flavorName }}



    - id: publish-pr

      name: Create GitOps Pull Request

      action: publish:github:pull-request

      input:

        repoUrl: github.com?repo=Abderraoufzekkour/idp-openstack

        branchName: add-vm-${{ parameters.instanceName }}

        title: "Deploy OpenStack VM: ${{ parameters.instanceName }}"

        description: "This PR was automatically generated by Backstage to provision a new OpenStack VM via Crossplane."



  output:

    links:

      - title: "Review & Merge PR in GitHub"

        url: ${{ steps['publish-pr'].output.remoteUrl }}

